import { describe, expect, it } from "vitest";
import py from "./py.json";
import { lines, parseEntries, parsePairLines, parseSkillGroups, splitLeadIn } from "../parse";

/**
 * The portfolio and the PDF read the same stored draft. `parse.ts` claimed to
 * mirror the Python that does it, and did not — a review found four
 * divergences, including a published page announcing that somebody worked at
 * "Company Name" and certifications printing "Cert | Issuer | 2026" verbatim.
 *
 * A claim of parity is worth nothing without something that checks it, so
 * these run the *real* Python output (py.json, generated by the script beside
 * it) against the TypeScript. Regenerate the fixture whenever a parser in
 * builder.py or _cvdesign.py changes; a failure here means the live page and
 * the downloaded document have started disagreeing, which is otherwise
 * completely silent.
 */

const ENTRIES = [
  "AI Data Engineer Intern | Aptiv | Jun 2026 - Present | Tangier, Morocco\n- Built a KPI platform.\n- Designed a module.",
  "Manager | Company Name | 2023 | Location",
  "Manager | Location Services Ltd | 2023",
  "Engineering Degree | EMSI, Casablanca | 2022\nSpecialization: AI & Data Science",
  "Intern | Web Agency | 2024 - 2025 - 1 month",
  "Role A | Org A | 2024\n- one\nRole B | Org B | 2025\n- two",
  "- an orphan bullet",
  "x".repeat(120) + " | Org | 2024",
  "",
];
const FLAT = ["N/A\nCity\n-\nReal thing", "- one\n\n• two\n  * three  ", "- • Nexora AI", ""];
const SKILLS = ["Languages & Frameworks: Python, Django\nData & ML: pandas, NumPy",
  "Data: PostgreSQL, Kafka\nETL, Airflow", "Python, SQL"];
const LEADS = ["Nexora AI — Call-center SaaS", "Nexora AI - Call-center SaaS",
  "Nexora AI—Call-center SaaS", "Call-center tooling", "Just a project name"];
const PAIRS = ["AWS Solutions Architect | Amazon | 2024", "Arabic | Native", "Arabic - Native"];

describe("differential parity against the real Python", () => {
  it("parseEntries matches parse_entries + _polish_entries", () => {
    expect(ENTRIES.map(parseEntries)).toEqual(py.entries);
  });
  it("lines matches _lines_of", () => {
    expect(FLAT.map(lines)).toEqual(py.flat);
  });
  it("parseSkillGroups matches _skill_groups", () => {
    expect(SKILLS.map((b) => parseSkillGroups(b).map((g) => [g.label, g.items.join(", ")])))
      .toEqual(py.skills);
  });
  it("splitLeadIn matches _split_lead", () => {
    expect(LEADS.map((l) => { const r = splitLeadIn(l); return [r.lead, r.rest]; }))
      .toEqual(py.leads);
  });
  it("parsePairLines matches _as_pair over _lines_of", () => {
    expect(PAIRS.map(parsePairLines)).toEqual(py.pairs);
  });
});
